[pytest]
DJANGO_SETTINGS_MODULE = studybud.settings
python_files = tests.py test_*.py *_tests.py
addopts = -q --disable-warnings --maxfail=1 --cov=base --cov-report=xml
markers =
    django_db: mark test as requiring database access